# Generated by Django 6.1 on 2026-08-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PARSING', 'Parsing'), ('STRUCTURING', 'Structuring'), ('VALIDATING', 'Validating'), ('CHUNKING', 'Chunking'), ('EMBEDDING', 'Embedding'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('parser_version', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('element_type', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='knowledge.document')),
            ],
            options={
                'ordering': ['page_number', 'order'],
            },
        ),
    ]
