# Generated by Django 6.1 on 2026-08-21 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('academic_year', models.CharField(default='1404-1405', max_length=20)),
                ('source_pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(blank=True, max_length=100, null=True)),
                ('section_type', models.CharField(choices=[('main_text', 'متن اصلی'), ('verse_reflection', 'تفکر در آیات و روایات'), ('review', 'بررسی و تطبیق'), ('thought_and_research', 'اندیشه و تحقیق'), ('activity', 'فعالیت کلاسی'), ('suggestion', 'پیشنهاد و مطالعه'), ('reading', 'استماع و قرائت')], default='main_text', max_length=50)),
                ('section_title', models.CharField(blank=True, max_length=250, null=True)),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['lesson', 'page_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentelement',
            name='document',
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(choices=[('khordad', 'خرداد'), ('shahrivar', 'شهریور'), ('dey', 'دی')], max_length=30)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='knowledge.book')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('descriptive', 'تشریحی'), ('fill_in_blank', 'جای خالی'), ('true_false', 'صحیح / غلط'), ('multiple_choice', 'چهارگزینه\u200cای'), ('verse_message', 'پیام آیه'), ('short_answer', 'پاسخ کوتاه')], default='descriptive', max_length=30)),
                ('score', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('topic_tags', models.JSONField(blank=True, default=list)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_answer', models.TextField()),
                ('rubric_breakdown', models.JSONField(blank=True, default=list)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_key', to='knowledge.examquestion')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='knowledge.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='book',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='knowledge.grade'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('part_title', models.CharField(blank=True, max_length=250, null=True)),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='knowledge.book')),
            ],
            options={
                'ordering': ['book', 'lesson_number'],
                'unique_together': {('book', 'lesson_number')},
            },
        ),
        migrations.AddField(
            model_name='examquestion',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_questions', to='knowledge.lesson'),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(default=0)),
                ('original_content', models.TextField()),
                ('contextual_content', models.TextField(blank=True, null=True)),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
                ('token_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding_vector', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.book')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.booksection')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.lesson')),
            ],
            options={
                'ordering': ['book', 'lesson', 'page_start', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='anonymous', max_length=100)),
                ('title', models.CharField(default='گفتگوی جدید', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.book')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='booksection',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='knowledge.lesson'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'معلم هوشمند'), ('system', 'سیستم')], max_length=20)),
                ('content', models.TextField()),
                ('intent_detected', models.CharField(blank=True, max_length=50, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='knowledge.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='MessageCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('quote_snippet', models.TextField()),
                ('relevance_score', models.FloatField(default=1.0)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='knowledge.documentchunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='knowledge.message')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='knowledge.subject'),
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.CharField(max_length=100)),
                ('ayah', models.IntegerField()),
                ('arabic_text', models.TextField(blank=True, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(max_length=200)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='knowledge.lesson')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='knowledge.booksection')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentElement',
        ),
    ]
